name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Fix workspace permissions
        run: docker run --rm -v $GITHUB_WORKSPACE:/workspace alpine chown -R $(id -u):$(id -g) /workspace || true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Build & Push Frontend
        run: |
          docker build -t localhost:5000/frontend:latest -f frontend/Dockerfile frontend/
          docker push localhost:5000/frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t localhost:5000/backend:latest -f backend/Dockerfile backend/
          docker push localhost:5000/backend:latest

      - name: Build & Push DB (Postgres)
        run: |
          docker build -t localhost:5000/db:latest -f backend/database.Dockerfile backend/
          docker push localhost:5000/db:latest

      - name: Install Terraform (if missing)
        run: |
          if ! command -v terraform &> /dev/null; then
            echo "Instalando Terraform..."
            wget -q https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
            unzip -q terraform_1.5.0_linux_amd64.zip
            mkdir -p $HOME/.local/bin
            mv terraform $HOME/.local/bin/
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          else
            echo "Terraform ya está instalado."
          fi

      - name: Terraform Init & Apply
        working-directory: infra/terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Restart Kubernetes Deployments
        run: |
          kubectl rollout restart deployment/frontend-deployment -n devops-app || true
          kubectl rollout restart deployment/backend-deployment -n devops-app || true
          kubectl rollout restart deployment/postgres-deployment -n devops-app || true
